# Generated by Django 5.1.2 on 2024-10-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='type',
        ),
        migrations.AddField(
            model_name='news',
            name='Category',
            field=models.TextField(default='kerala'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.CharField(max_length=1000),
        ),
    ]
